import { EmbeddedModule } from '@/components/embedded-module';
import { capereFetch, Envelope } from '@/lib/api';

const sections = [['Overview','overview'],['Technical SEO','technical'],['Keywords','keywords'],['Competitors','competitors'],['GBP','gbp'],['Recommendations','recommendations'],['History','history']] as const;
type Metric={metric_name:string;metric_value:string;metric_date:string};
type Audit={id:string;status:string;score:number|null;issue_count:number|null;completed_at:string|null;started_at:string;site_url?:string;summary?:unknown};
type Integration={provider:string;status:string;last_sync_at:string|null;last_error:string|null};

const Icon=({name}:{name:string})=><span aria-hidden style={{fontSize:22}}>{({clicks:'↗',impressions:'◉',position:'⌖',health:'✓',audit:'⌕',keywords:'⌨',competitors:'◎',gbp:'★',recommendations:'✦',history:'◷'} as Record<string,string>)[name]??'•'}</span>;
const Card=({title,value,detail,icon}:{title:string;value:string;detail:string;icon:string})=><div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div className="eyebrow">{title}</div><Icon name={icon}/></div><div style={{fontSize:30,fontWeight:750,margin:'10px 0 4px'}}>{value}</div><p style={{margin:0}}>{detail}</p></div>;
const Bar=({label,value,max,detail}:{label:string;value:number;max:number;detail?:string})=><div style={{marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',gap:12,fontSize:13}}><span>{label}</span><strong>{detail??value}</strong></div><div style={{height:8,background:'var(--border)',borderRadius:99,overflow:'hidden',marginTop:6}}><div style={{width:`${Math.max(2,Math.min(100,max?value/max*100:0))}%`,height:'100%',background:'linear-gradient(90deg,#6d5dfc,#26c6a0)',borderRadius:99}}/></div></div>;
const Panel=({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode})=><div className="card"><div style={{display:'flex',gap:10,alignItems:'center'}}><Icon name={title.toLowerCase().includes('keyword')?'keywords':title.toLowerCase().includes('technical')?'audit':'recommendations'}/><div><h3 style={{margin:0}}>{title}</h3><p style={{margin:'4px 0 0'}}>{subtitle}</p></div></div><div style={{marginTop:18}}>{children}</div></div>;

export default async function SeoPage({searchParams}:{searchParams:Promise<{view?:string}>}){
 const view=(await searchParams).view??'overview'; let summary:Envelope<Record<string,unknown>>|null=null;
 try{summary=await capereFetch('/api/v1/command-centers/seo-command-center/summary');}catch{}
 const d=summary?.data??{}; const metrics=(Array.isArray(d.metrics)?d.metrics:[]) as Metric[];
 const latest=(name:string)=>metrics.find(x=>x.metric_name===name)?.metric_value;
 const series=(name:string)=>metrics.filter(x=>x.metric_name===name).slice().reverse();
 const audit=(d.technicalAudit&&typeof d.technicalAudit==='object'?d.technicalAudit:null) as Audit|null;
 const history=(Array.isArray(d.auditHistory)?d.auditHistory:[]) as Audit[];
 const keywords=(Array.isArray(d.keywords)?d.keywords:[]) as Array<{keyword:string;rank:number|null;checked_on:string|null;url:string|null}>;
 const competitors=(Array.isArray(d.competitors)?d.competitors:[]) as Array<{domain:string;name:string|null;last_checked_at:string|null}>;
 const integrations=(Array.isArray(d.integrations)?d.integrations:[]) as Integration[];
 const recs=(Array.isArray(d.recommendations)?d.recommendations:[]) as Array<{id:string;title:string;action:string;priority:string;rationale?:string}>;
 const connected=(p:string)=>integrations.some(x=>x.provider===p&&x.status==='connected');
 const clicks=latest('clicks')??'0', impressions=latest('impressions')??'0', position=latest('position')??'—';
 const tabs=sections.map(([label,key])=>({label,href:key==='overview'?'/seo':`/seo?view=${key}`,active:view===key}));
 const score=audit?.score??0, issues=audit?.issue_count??0;
 let content:React.ReactNode;
 if(view==='technical') content=<div className="grid"><div className="grid grid-3"><Card title="Health score" value={`${score}/100`} detail="Latest DataForSEO crawl" icon="health"/><Card title="Issues detected" value={String(issues)} detail={issues?'Review prioritized findings':'No counted issues in summary'} icon="audit"/><Card title="Last audit" value={audit?.completed_at?new Date(audit.completed_at).toLocaleDateString():'Not run'} detail={audit?.site_url??'Configure a website'} icon="history"/></div><Panel title="Technical audit interpretation" subtitle="What the latest crawl means for search engines and visitors."><p>{audit?score===0&&issues===0?'The provider completed the crawl but returned no usable health score or counted issues. This usually means the summary payload is sparse, the site exposed too few crawlable pages, or additional page-level endpoints are needed for detailed findings. The audit is operational, but this result should be treated as inconclusive—not as a perfect or failed site.':'Your technical score summarizes crawlability, metadata, links, performance signals, and indexing checks. Address higher-impact issues first.':'No completed technical audit is available yet.'}</p>{audit&&<><Bar label="Technical health" value={score} max={100} detail={`${score}/100`}/><Bar label="Crawl issue load" value={Math.min(issues,100)} max={100} detail={`${issues} issues`}/></>}</Panel></div>;
 else if(view==='keywords') content=<div className="grid"><div className="grid grid-3"><Card title="Tracked keywords" value={String(keywords.length)} detail={keywords.length?'Latest stored rankings':'GSC query metrics are connected'} icon="keywords"/><Card title="Average position" value={position} detail="Lower is better" icon="position"/><Card title="Search impressions" value={impressions} detail="Visibility in Google Search" icon="impressions"/></div><Panel title="Keyword visibility" subtitle="Queries and rankings collected from connected search providers.">{keywords.length?<div>{keywords.map((k,i)=><Bar key={`${k.keyword}-${i}`} label={k.keyword} value={Math.max(0,101-(k.rank??100))} max={100} detail={k.rank?`Position ${k.rank}`:'Awaiting rank'}/>)}</div>:<p>Search Console is connected and has begun collecting search performance. The property currently reports {impressions} impression(s), {clicks} click(s), and an average position of {position}. Keyword-level rows will appear as more query data is synchronized.</p>}</Panel></div>;
 else if(view==='competitors') content=<div className="grid"><div className="grid grid-3"><Card title="Competitors monitored" value={String(competitors.length)} detail="Saved comparison domains" icon="competitors"/><Card title="Search position" value={position} detail="Your current average position" icon="position"/><Card title="Data readiness" value={competitors.length?'Active':'Setup needed'} detail="Add competitor domains for comparisons" icon="audit"/></div><Panel title="Competitive visibility" subtitle="Compare domains, rankings, and search overlap.">{competitors.length?competitors.map(c=><div key={c.domain} style={{display:'flex',justifyContent:'space-between',padding:'12px 0',borderBottom:'1px solid var(--border)'}}><strong>{c.name??c.domain}</strong><span>{c.last_checked_at?new Date(c.last_checked_at).toLocaleDateString():'Awaiting check'}</span></div>):<p>Your technical project is active for {audit?.site_url??'the configured site'}, but no competitor domains have been saved yet. Add direct local and organic-search competitors to unlock share-of-visibility and keyword-gap reporting.</p>}</Panel></div>;
 else if(view==='gbp') content=<div className="grid"><div className="grid grid-3"><Card title="GBP connection" value={connected('google_business_profile')?'Connected':'Not connected'} detail="Google Business Profile" icon="gbp"/><Card title="Local reviews" value="—" detail="Available after GBP sync" icon="gbp"/><Card title="Local actions" value="—" detail="Calls, directions, and website visits" icon="clicks"/></div><Panel title="Local search presence" subtitle="Reviews and customer actions from Google Business Profile."><p>{connected('google_business_profile')?'GBP is connected. Local metrics will populate after the next provider sync.':'Connect a Google Business Profile location to measure ratings, review velocity, calls, directions, and local discovery. Technical SEO and Search Console remain active independently.'}</p></Panel></div>;
 else if(view==='recommendations') content=<div className="grid"><div className="grid grid-3"><Card title="Open recommendations" value={String(recs.length)} detail="SEO actions awaiting review" icon="recommendations"/><Card title="Audit status" value={audit?'Complete':'Pending'} detail={audit?`${issues} issues summarized`:'Run technical audit'} icon="audit"/><Card title="Search signal" value={`${impressions} impressions`} detail={`${clicks} organic clicks`} icon="clicks"/></div>{recs.length?recs.map(r=><Panel key={r.id} title={r.title} subtitle={`${r.priority} priority`}><p>{r.rationale}</p><strong>Recommended action</strong><p>{r.action}</p></Panel>):<Panel title="What to do next" subtitle="Grounded guidance from the data currently available."><p>{score===0&&issues===0?'The crawl completed but its summary is inconclusive. Run a deeper page-level extraction before making technical changes. Meanwhile, continue collecting Search Console data and confirm important pages are indexed.':'No actionable SEO insight has crossed the recommendation threshold yet. This is not an error; recommendations appear only when the system has enough evidence.'}</p></Panel>}</div>;
 else if(view==='history') content=<div className="grid"><div className="grid grid-3"><Card title="Audits completed" value={String(history.filter(x=>x.status==='succeeded').length)} detail="Recent retained runs" icon="history"/><Card title="Latest score" value={String(score)} detail="Technical health" icon="health"/><Card title="Latest issues" value={String(issues)} detail="Detected crawl issues" icon="audit"/></div><Panel title="Audit timeline" subtitle="Technical audit status and results over time.">{history.length?history.map(h=><div key={h.id} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:16,padding:'14px 0',borderBottom:'1px solid var(--border)'}}><div><strong>{h.status==='succeeded'?'Completed audit':'Audit run'}</strong><div style={{fontSize:13,opacity:.7}}>{new Date(h.completed_at??h.started_at).toLocaleString()}</div></div><span>Score {h.score??'—'}</span><span>{h.issue_count??0} issues</span></div>):<p>No audit history is available.</p>}</Panel></div>;
 else {const clickSeries=series('clicks');content=<div className="grid"><div className="grid grid-4"><Card title="Organic clicks" value={clicks} detail="Visits from Google Search" icon="clicks"/><Card title="Impressions" value={impressions} detail="Times shown in search" icon="impressions"/><Card title="Average position" value={position} detail="Average Google ranking" icon="position"/><Card title="Technical health" value={`${score}/100`} detail={audit?`${issues} issues · audit complete`:'Audit not completed'} icon="health"/></div><div className="grid grid-2"><Panel title="Search performance" subtitle="Recent organic visibility from Search Console.">{clickSeries.length?clickSeries.map((m,i)=><Bar key={`${m.metric_date}-${i}`} label={m.metric_date} value={Number(m.metric_value)} max={Math.max(...clickSeries.map(x=>Number(x.metric_value)),1)} detail={`${m.metric_value} clicks`}/>):<p>Search Console is connected but the property has very little historical traffic so far. Current totals are {clicks} clicks and {impressions} impression(s).</p>}</Panel><Panel title="SEO readiness" subtitle="Provider coverage across your command center."><Bar label="Search Console" value={connected('google_search_console')?100:0} max={100} detail={connected('google_search_console')?'Connected':'Not connected'}/><Bar label="Technical audit" value={audit?100:0} max={100} detail={audit?'Completed':'Pending'}/><Bar label="Google Business Profile" value={connected('google_business_profile')?100:0} max={100} detail={connected('google_business_profile')?'Connected':'Not connected'}/><Bar label="Competitor tracking" value={competitors.length?100:0} max={100} detail={competitors.length?'Active':'Not configured'}/></Panel></div><Panel title="Executive interpretation" subtitle="What the current SEO evidence says."><p>Google Search Console is connected and reporting early visibility: {impressions} impression(s), {clicks} click(s), and average position {position}. The technical audit completed for {audit?.site_url??'your website'} with score {score}; because it reported {issues} counted issues alongside a zero score, treat the technical result as incomplete evidence until page-level findings are collected. GBP and competitor coverage remain the largest data gaps.</p></Panel></div>}
 return <EmbeddedModule product="SEO Command Center" title="Search visibility, made actionable" description="Technical health, rankings, competitors, and local presence for your firm." tabs={tabs}>{content}</EmbeddedModule>;
}
