type PlaceReview={id:string;rating:number;author:string|null;comment:string|null;publishedAt:string|null;relativeTime:string|null;authorPhoto:string|null};
type GoogleProfile={available:boolean;setupRequired:boolean;placeId:string;name:string|null;description:string|null;primaryCategory:string|null;categories:string[];address:string|null;phone:string|null;website:string|null;mapsUrl:string|null;businessStatus:string|null;openNow:boolean|null;openingHours:string[];rating:number;reviewCount:number;photos:Array<{name:string;width:number|null;height:number|null}>;reviews:PlaceReview[];message?:string};
export type BusinessProfileData={connected:boolean;dataAvailable:boolean;accessStatus:'available'|'permission_required'|'temporarily_unavailable';profileConnectionConfirmed:boolean;locationName?:string|null;reviewCount:number;averageRating:number;unanswered:number;responseRate:number;ratingDistribution:Record<'1'|'2'|'3'|'4'|'5',number>;monthlyTrend:Array<{month:string;count:number;averageRating:number}>;message?:string;business?:{name:string|null;website:string|null;email:string|null;phone:string|null;address:string|null;city:string|null;state:string|null;country:string|null;postalCode:string|null;timezone:string|null;logoUrl:string|null;googlePlacesId:string|null;social:Record<string,string>};googleProfile?:GoogleProfile};
const Panel=({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode})=><div className="card seo-panel"><div className="seo-panel-header"><div><h3>{title}</h3><p>{subtitle}</p></div></div><div className="seo-panel-body">{children}</div></div>;
const Card=({title,value,detail}:{title:string;value:string;detail:string})=><div className="card seo-metric-card"><div className="metric-label">{title}</div><div className="seo-metric-value">{value}</div><p className="seo-metric-detail">{detail}</p></div>;
const StatusList=({items}:{items:Array<{label:string;value:string;status:'good'|'warning'|'neutral';detail:string}>})=><div className="status-list">{items.map(item=><div className="status-row" key={item.label}><span className={`status-indicator ${item.status}`} aria-hidden/><div className="status-copy"><strong>{item.label}</strong><span>{item.detail}</span></div><span className={`status-value ${item.status}`}>{item.value}</span></div>)}</div>;
const RatingTrend=({points}:{points:Array<{month:string;averageRating:number;count:number}>})=>{if(points.length<2)return <p className="muted">A trend will appear after reviews are available across more than one month.</p>;const width=640,height=190,pad=28,step=(width-pad*2)/(points.length-1);const plotted=points.map((point,index)=>({...point,x:pad+index*step,y:height-pad-(point.averageRating/5)*(height-pad*2)}));const path=plotted.map((point,index)=>`${index?'L':'M'} ${point.x} ${point.y}`).join(' ');return <div className="seo-line-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Average customer rating by month"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} className="chart-axis"/><path d={path} className="chart-line"/>{plotted.map((point,index)=><g className="chart-point" key={point.month}><circle cx={point.x} cy={point.y} r="5"><title>{point.month}: {point.averageRating.toFixed(1)} from {point.count} reviews</title></circle>{(index===0||index===plotted.length-1||index%Math.max(1,Math.ceil(plotted.length/5))===0)&&<text x={point.x} y={height-5} textAnchor="middle">{new Date(`${point.month}-01T00:00:00Z`).toLocaleDateString(undefined,{month:'short',year:'2-digit'})}</text>}</g>)}</svg></div>};
const photoUrl=(name:string,width=1200)=>`/api/capere/command-centers/ai-cmo/business-profile/photo?name=${encodeURIComponent(name)}&width=${width}`;

export function BusinessProfileDashboard({profile}:{profile:BusinessProfileData|null}){
  const ghl=profile?.business,google=profile?.googleProfile,listing=google?.available?google:null;
  const socialEntries=Object.entries(ghl?.social??{}).filter(([key,value])=>Boolean(value)&&key!=='googlePlacesId');
  const fields=[listing?.name,listing?.description,listing?.primaryCategory,listing?.address,listing?.phone,listing?.website,listing?.openingHours.length,listing?.photos.length,listing?.rating,listing?.reviewCount,listing?.mapsUrl,ghl?.googlePlacesId];
  const completed=fields.filter(Boolean).length,completeness=Math.round((completed/fields.length)*100);
  const rating=listing?.rating||(profile?.dataAvailable?profile.averageRating:0),reviewCount=listing?.reviewCount||(profile?.dataAvailable?profile.reviewCount:0);
  const heroPhoto=listing?.photos[0]?.name;
  const checks:Array<[string,boolean]>=[['Business name',Boolean(listing?.name)],['Description',Boolean(listing?.description)],['Primary category',Boolean(listing?.primaryCategory)],['Phone and website',Boolean(listing?.phone&&listing?.website)],['Opening hours',Boolean(listing?.openingHours.length)],['Business photos',Boolean(listing?.photos.length)],['Google Maps link',Boolean(listing?.mapsUrl)],['Customer reviews',reviewCount>0]];
  return <div className="grid business-profile-layout">
    {!listing&&<div className="card cmo-provider-warning"><strong>Google Business Profile details are not available yet</strong><p>{google?.message??(ghl?.googlePlacesId?'The Capere administrator needs to enable Google Places API access.':'GoHighLevel has not provided a Google Place ID for this business.')}</p></div>}
    <section className="card business-profile-hero"><div className="business-profile-brand">{heroPhoto?<img src={photoUrl(heroPhoto,400)} alt=""/>:ghl?.logoUrl?<img src={ghl.logoUrl} alt=""/>:<span>{(listing?.name??ghl?.name??profile?.locationName??'B').slice(0,1).toUpperCase()}</span>}</div><div><div className="eyebrow">Google Business Profile</div><h2>{listing?.name??'Listing details unavailable'}</h2><p>{listing?.description??listing?.address??'Connect the GHL location to a Google business listing to show its public profile.'}</p><div className="business-profile-badges">{listing?.primaryCategory&&<span className="badge">{listing.primaryCategory}</span>}<span className={`badge ${listing?.businessStatus==='Operational'?'good':''}`}>{listing?.businessStatus??'Status unavailable'}</span>{listing?.openNow!==null&&listing?.openNow!==undefined&&<span className={`badge ${listing.openNow?'good':''}`}>{listing.openNow?'Open now':'Closed now'}</span>}</div></div><div className="profile-score"><strong>{completeness}%</strong><span>Listing coverage</span></div></section>
    <div className="grid grid-4"><Card title="Google rating" value={rating?`${rating.toFixed(1)}/5`:'—'} detail={reviewCount?`${reviewCount.toLocaleString()} public ratings`:'No rating returned'}/><Card title="Profile category" value={listing?.primaryCategory??'—'} detail={listing?.categories.slice(1,3).join(' · ')||'No secondary categories returned'}/><Card title="Business photos" value={listing?String(listing.photos.length):'—'} detail="Photos returned by Google Places"/><Card title="Review response rate" value={profile?.dataAvailable?`${Math.round(profile.responseRate*100)}%`:'—'} detail={profile?.dataAvailable?`${profile.unanswered} GHL reviews awaiting replies`:'Requires GHL reputation permission'}/></div>
    <div className="business-profile-columns"><Panel title="Google listing information" subtitle="Public details returned for the business listing identified through GoHighLevel."><div className="business-detail-list">{[['Business name',listing?.name],['Description',listing?.description],['Primary category',listing?.primaryCategory],['Address',listing?.address],['Phone',listing?.phone],['Website',listing?.website],['Google Maps',listing?.mapsUrl],['Business status',listing?.businessStatus]].map(([key,value])=><div key={key}><span>{key}</span><strong>{value||'Not returned by Google'}</strong></div>)}</div></Panel><Panel title="GBP optimization coverage" subtitle="A practical check of important public listing elements."><div className="profile-completeness"><div className="profile-ring" style={{'--score':`${completeness*3.6}deg`} as React.CSSProperties}><strong>{completeness}%</strong></div><div className="profile-checks">{checks.map(([text,ready])=><div key={text} className={ready?'complete':'missing'}><span/><strong>{text}</strong><small>{ready?'Available':'Needs attention'}</small></div>)}</div></div></Panel></div>
    <div className="business-profile-columns"><Panel title="Opening hours" subtitle="Regular or current hours returned by Google.">{listing?.openingHours.length?<div className="business-detail-list business-hours">{listing.openingHours.map(day=>{const [name,...hours]=day.split(':');return <div key={day}><span>{name}</span><strong>{hours.join(':').trim()||'Closed'}</strong></div>})}</div>:<p className="muted">Opening hours were not returned for this listing.</p>}</Panel><Panel title="Social and connected profiles" subtitle="Social links are provided by GoHighLevel; Google Places does not publish them."><div className="business-channel-list">{socialEntries.map(([key,value])=><div key={key}><strong>{key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}</strong><span>{value}</span></div>)}{!socialEntries.length&&<p className="muted">No social profile links are stored in the connected GoHighLevel location.</p>}</div></Panel></div>
    <Panel title="Business photos" subtitle="Public photos associated with the Google listing.">{listing?.photos.length?<div className="business-photo-grid">{listing.photos.map(photo=><img key={photo.name} src={photoUrl(photo.name)} alt={`${listing.name??'Business'} Google profile`}/>)}</div>:<p className="muted">No public business photos were returned.</p>}</Panel>
    <div className="business-profile-columns"><Panel title="Public review snapshot" subtitle="Selected reviews returned by Google Places.">{listing?.reviews.length?<div className="profile-review-list">{listing.reviews.map(review=><article key={review.id}>{review.authorPhoto?<img src={review.authorPhoto} alt=""/>:<span>{(review.author??'G').slice(0,1)}</span>}<div><strong>{review.author??'Google customer'} · {review.rating.toFixed(1)}/5</strong><p>{review.comment||'Rating provided without written feedback.'}</p><small>{review.relativeTime??(review.publishedAt?new Date(review.publishedAt).toLocaleDateString():null)}</small></div></article>)}</div>:<p className="muted">Google did not return a public review sample.</p>}</Panel><Panel title="Review rating trend" subtitle="Trend available from GHL Reputation after review access is approved."><RatingTrend points={profile?.monthlyTrend??[]}/></Panel></div>
    <Panel title="Data sources" subtitle="Where each part of this profile comes from."><StatusList items={[{label:'Google listing details',value:listing?'Available':google?.setupRequired?'Admin setup required':'Unavailable',status:listing?'good':'warning',detail:'Name, description, categories, address, phone, website, hours, photos, rating and selected reviews via Google Places'},{label:'Google listing identity',value:ghl?.googlePlacesId?'Provided by GHL':'Missing',status:ghl?.googlePlacesId?'good':'warning',detail:'GoHighLevel supplies the Google Place ID used to locate the public listing'},{label:'Review reply analytics',value:profile?.accessStatus==='available'?'Available':profile?.accessStatus==='permission_required'?'Permission needed':'Unavailable',status:profile?.accessStatus==='available'?'good':'warning',detail:'Response rate and unanswered reviews via GHL Reputation'},{label:'Social profile links',value:socialEntries.length?'Available from GHL':'Not provided',status:socialEntries.length?'good':'neutral',detail:'Social profiles are location metadata from GoHighLevel, not Google Business Profile data'}]}/></Panel>
  </div>;
}
